### ISSUE TITLE
Long-running Mi Bulbs crashes homebridge server

### ISSUE THREAD

**Issue by fnowacki** [vieira/homebridge-yeelight-wifi#123]
Hi!

I have two Mi Bulbs that periodically crash the homebridge server, log:
```
[10/13/2024, 12:26:10 PM] Error: 4
0|api      |     at Bulb.sendCmd (/home/pi/homebridge/node_modules/homebridge-yeelight-wifi/bulbs/bulb.js:172:27)
0|api      |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|api      |     at Bulb.initMoonlight (/home/pi/homebridge/node_modules/homebridge-yeelight-wifi/bulbs/moonlight.js:12:28)
0|api      | [10/13/2024, 12:26:10 PM] [Yeelight] 192.168.99.111 closed. error? false.
0|api      | error Command failed with exit code 143.
0|api      | warning package.json: No license field
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] { id: 3, error: { code: -1, message: 'client quota exceeded' } }
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] 0x000000001c0a6e9d: failed to send cmd 3 after 5 retries.
0|api      | [10/13/2024, 12:26:20 PM] Error: 3
0|api      |     at Bulb.sendCmd (/home/pi/homebridge/node_modules/homebridge-yeelight-wifi/bulbs/bulb.js:172:27)
0|api      |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|api      |     at Bulb.initMoonlight (/home/pi/homebridge/node_modules/homebridge-yeelight-wifi/bulbs/moonlight.js:12:28)
0|api      | [10/13/2024, 12:26:20 PM] [Yeelight] 192.168.99.111 closed. error? false.
0|api      | error Command failed with exit code 143.
```

As a fix, I restart the bulbs by unplugging them from the power for a few seconds. After ~2-3 months, the issue happens again 😅

**Comment by movy** [comment]
Just experienced this today, looks like a bug in lamp firmware, but this plugin might be able to circumvent it.

Will leave it here, in case this problem becomes annoying and we need to patch it on plugin side.
https://forum.yeelight.com/t/topic/15756/26

**Comment by okonet** [comment]
The same happened to me a few times with the Floor Lamp. I'll try to fix this with AI.

EDIT: After looking into the forum topic, I'm not sure what's the solution on the plugin side could be. I guess the best we could do is to swallow the error so at least not affected devices continue to work?

**Comment by movy** [comment]
@okonet , I think swallowing and backoff retries to whatever API complains `client quota exceeded` should work.. it's better not to fulfil user's request and be ready for another request, rather than to crash and become completely unresponsive. Thanks for looking into this!
