### ISSUE TITLE
Plugin does not work after update

### ISSUE THREAD

**Issue by skop1986** [vieira/homebridge-yeelight-wifi#30]
Hi! After updating the plug-in, the lamps stopped turning on ) how can I fix this?

Load homebridge-yeelight.yeelight
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] starting YeePlatform using homebridge API v2.2
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 30d3d3.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 3607fd.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 1b09e4.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 3610ae.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 35bb9b.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] remembered device 708b38.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] doing a round of proactive search for known devices.
Uncaught Exception { Error: setMulticastInterface EADDRNOTAVAIL
    at Socket.setMulticastInterface (dgram.js:601:11)
    at Socket.serverAqaraLANProtocolSocket.on (/usr/lib/node_modules/homebridge-mi-aqara/index.js:194:42)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at startListening (dgram.js:156:10)
    at _handle.lookup (dgram.js:273:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'setMulticastInterface' }
[2019-1-24 09:48:21] [Broadlink RM] TV On/Off getSwitchState: false
[2019-1-24 09:48:21] [Broadlink RM] Vol Up getSwitchState: false
[2019-1-24 09:48:21] [Broadlink RM] TV Vol Down getSwitchState: false
[2019-1-24 09:48:21] Cam is running on port 38935.
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 30d3d3.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 3607fd.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 35bb9b.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 35bb9b.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 30d3d3.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 1b09e4.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 1b09e4.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 3610ae.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2019-1-24 09:48:21] [homebridge-yeelight.yeelight] received advertisement from 3607fd.
Uncaught Exception TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/usr/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/usr/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/usr/l

**Comment by GreatCookie** [comment]
Same error from my side - had to uninstall and roll back to previous version for the time-being. Will wait for the next release.

**Comment by skop1986** [comment]
I also did downgrade to version 1.0.5

**Comment by Shobba** [comment]
Was able to fix this by adding the yeelight plattform to the homebridge config like this:

```
"accessories": [],
"platforms": [
        {
            "platform": "yeelight",
            "name": "Yeelight"
        }
]
```

**Comment by skop1986** [comment]
> Was able to fix this by adding the yeelight plattform to the homebridge config like this:
> 
> ```
> "accessories": [],
> "platforms": [
>         {
>             "platform": "yeelight",
>             "name": "Yeelight"
>         }
> ]
> ```

thanks, it solved the problem

**Comment by vieira** [comment]
Thanks @Shobba!
