### ISSUE TITLE
Cannot read property 'defaultValue' of null

### ISSUE THREAD

**Issue by shtefanilie** [vieira/homebridge-yeelight-wifi#31]
Just after I installed it, this appeared:
```
[2019-1-27 16:58:34] [homebridge-yeelight.yeelight] doing a round of proactive search for known devices.
[2019-1-27 16:58:34] Homebridge is running on port 46475.
[2019-1-27 16:58:34] [homebridge-yeelight.yeelight] received advertisement from c881cc.
/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/homebridge-yeelight-wifi/utils.js:22
  (config.defaultValue
          ^

TypeError: Cannot read property 'defaultValue' of null
    at blacklist (/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/homebridge-yeelight-wifi/utils.js:22:11)
    at YeePlatform.buildDevice (/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/homebridge-yeelight-wifi/platform.js:89:20)
    at YeePlatform.handleMessage (/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/homebridge-yeelight-wifi/platform.js:84:10)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)```

**Comment by GreatCookie** [comment]
Believe this is the same as Issue #30 
Had to uninstall and downgrade to the previous release.

**Comment by Shobba** [comment]
Was able to fix this by adding the yeelight plattform to the homebridge config like this:

```
"accessories": [],
"platforms": [
        {
            "platform": "yeelight",
            "name": "Yeelight"
        }
]
```

**Comment by vieira** [comment]
Thanks!
