### ISSUE TITLE
Homebridge 1.3.1 warnings every minute

### ISSUE THREAD

**Issue by TzachiGuetta** [vieira/homebridge-yeelight-wifi#92]
[23/02/2021, 10:47:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:47:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:48:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:48:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:49:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:49:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:50:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 10:50:06] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**_### DEBUG MODE:_**

[23/02/2021, 13:27:30] [Yeelight] {"method":"set_ct_abx","params":[5524.861878453039,"smooth",400],"id":14}
[23/02/2021, 13:27:30] [Yeelight] { id: 14, result: [ 'ok' ] }
[23/02/2021, 13:27:30] [homebridge-yeelight-wifi] This plugin generated a warning from the characteristic 'Color Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[23/02/2021, 13:27:30] [homebridge-yeelight-wifi] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1645:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-yeelight-wifi/bulbs/temperature.js:20:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by TzachiGuetta** [comment]
@okonet

**Comment by okonet** [comment]
Feel free to dig deeper and fix those! :)

**Comment by TzachiGuetta** [comment]
@okonet teach me how to fix

in order to reproduce the issue:
- the bulb can be off\on state
- adaptive lightning is enabled
- adaptive lightning is selected per bulb

meaning: the issue is relevant only when 'adaptive lightning' is selected on bulb

**Comment by okonet** [comment]
Adaptive lightning is a feature of homebridge which sets CT on devices automatically every minute. You can't control it, so I think the issue isn't really in it but in the way the set request is handled in this library. I have no idea myself how to fix it.

**Comment by TzachiGuetta** [comment]
@okonet Its an homebridge issue?

**Comment by okonet** [comment]
No, I don’t think. They started to issue warning with the v1.3 that’s why it started to be visible.

**Comment by vieira** [comment]
This is probably caused by passing a second argument to the `callback` when setting characteristics, I'll open a PR if someone can test, as I don't have access to the the bulbs at the moment.

 https://github.com/vieira/homebridge-yeelight-wifi/blob/67ff4b470f0d34bb87a01fb41d230fe695dc568d/bulbs/temperature.js#L18-L25

**Comment by okonet** [comment]
Ah that would make sense! Thanks for pointing out.

**Comment by TzachiGuetta** [comment]
> This is probably caused by passing a second argument to the `callback` when setting characteristics, I'll open a PR if someone can test, as I don't have access to the the bulbs at the moment.
> 
> https://github.com/vieira/homebridge-yeelight-wifi/blob/67ff4b470f0d34bb87a01fb41d230fe695dc568d/bulbs/temperature.js#L18-L25

@vieira can you tag it? I will test

**Comment by vieira** [comment]
I have sent a request for review to @okonet, as he is maintaining this now I will let him handle it as any other PR.
